# Copied from PyRS
language: python
dist: trusty

services:
  - xvfb

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
  - env: CONDA=3.6

before_install:
- |
  # Install conda
  "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
  wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda init bash
install:
    # Setup conda activate/deactivate commands
  - conda init bash
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda info --root

    # Conda config - behavior and channel setup
  - conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
  - conda config --add channels conda-forge --add channels mantid --add channels mantid/label/nightly

script:
    # TEST: Create test environment and test build
  - conda create -q -n PyQtTools_test python=$CONDA qtpy pyside2 matplotlib flake8 pytest pytest-qt mypy pytest-cov codecov
  - conda info --envs
  - conda activate PyQtTools_test
  - python --version

  - |
    export DISPLAY=:99.0
    sleep 3
  # lint the code and generate an error if a warning is introduced
  - flake8 . --count
  # static analysis for typing
  - mypy pyqt_widgets tests

  # run some basic import tests to confirm things are working
  - python -c "import qtpy"

  # run pyqt_tools tests
  - xvfb-run --server-args="-screen 0 640x480x24" --auto-servernum pytest --cov=pyqt_widgets tests --disable-pytest-warnings -vv -r w

after_success:
  - codecov
